topic:
  # use your studentId <student-id>-users
  # hmm, had to manually create this topic locally
  name: ssherwood-users
  partitions-num: 6
  replication-factor: 3
server:
  port: 9080
spring:
  kafka:
    missingTopicsFatal: false
    bootstrap-servers:
      - localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
    consumer:
      # use your studentId <student-id>-group_id
      group-id: ssherwood-group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    template:
      default-topic:
logging:
  level:
    root: info